# Generated by Django 5.0.3 on 2024-03-13 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRegistrationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Father_Name", models.CharField(max_length=100)),
                ("Father_Age", models.CharField(max_length=100)),
                ("Mother_Name", models.CharField(max_length=100)),
                ("Mother_Age", models.CharField(max_length=100)),
                ("loginid", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("mobile", models.CharField(max_length=100, unique=True)),
                ("email", models.CharField(max_length=100, unique=True)),
                ("locality", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=1000)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "UserRegistrations",
            },
        ),
        migrations.CreateModel(
            name="UserTextDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_data", models.TextField()),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.userregistrationmodel",
                    ),
                ),
            ],
            options={
                "db_table": "usertestcaptions",
            },
        ),
    ]
