# Generated by Django 5.0.3 on 2024-03-16 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userregistrationmodel",
            old_name="Father_Age",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="userregistrationmodel",
            name="Father_Name",
        ),
        migrations.RemoveField(
            model_name="userregistrationmodel",
            name="Mother_Age",
        ),
        migrations.RemoveField(
            model_name="userregistrationmodel",
            name="Mother_Name",
        ),
    ]
